name: "Ory CLI"
description: "Authenticate and run Ory CLI commands"
author: "Luka Giorgadze"
branding:
  icon: "command"
  color: "gray-dark"
inputs:
  username:
    description: "Ory username"
    required: true
  password:
    description: "Ory password"
    required: true
  commands:
    description: "Newline-separated list of Ory CLI commands to run"
    required: true
runs:
  using: "composite"
  steps:
    - run: sudo apt-get install -y expect
      shell: bash
    - run: bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b . ory && sudo mv ./ory /usr/local/bin/
      shell: bash
    - run: |
        /usr/bin/expect <<'EOF'
        spawn ory auth
        expect "Do you want to sign in to an existing Ory Network account?"
        send -- "y\r"
        expect "Email:"
        send -- "${{ inputs.username }}\r"
        expect "Password:"
        send -- "${{ inputs.password }}\r"
        expect eof
        EOF
      shell: bash
    - name: Run commands
      run: |
        IFS=$'\n'
        for command in $COMMANDS
        do
          eval "/usr/local/bin/ory $command"
        done
      shell: bash
      env:
        COMMANDS: ${{ inputs.commands }}
